# Generated by Django 4.2.1 on 2023-08-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('periodo_ingresso', models.CharField(max_length=50, verbose_name='Período de Ingresso')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota - Web Avançado')),
                ('situacao', models.CharField(max_length=50, verbose_name='Situacao')),
            ],
        ),
    ]
