# Generated by Django 4.2.1 on 2023-08-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
